### ISSUE TITLE
Store all session data in Customizer settings

### ISSUE THREAD

**Issue by westonruter** [voldemortensen/menu-customizer#67]
There are currently Ajax requests that persist data out-of-band with Customizer session. These Ajax requests sent in response to creating new menus and updating menu items that result in persistent database changes. This runs against grain of the Customizer in which all user interactions in the Customizer should not be persistent until the user hits Save & Publish. For instance, if you create a new Menu then when you reload the Customizer you'll currently see the created menu there, even though you didn't hit Save & Publish.

In order to accomplish this, all unsaved menus and menu items would have to exist virtually when the Customizer preview runs. Previewing such settings would likely need to hook into the `pre_wp_nav_menu` filter to collect the menu items from Customizer settings as opposed to the menu items via `wp_get_nav_menu_items()`, or else a `wp_get_nav_menu_items` filter could be added which added some pseudo posts to the items array.

This also means that the existing functions used in Core for updating a nav menu item (e.g. `wp_update_nav_menu_object()` and `wp_update_nav_menu_item()`) would likely not be usable since they write out the changes to the database. And this would mean incompatibility with plugins that hook into menu items that are saved.

By switching to fully represent menu data in settings, we'll also more easily be able to preview changes to menus because all of the settings will be represented in the setting itself, as an array of menu data. Additionally, the Customizer is model-driven: when a setting changes its value, the controls are supposed to update to reflect that change, and vice-versa. However, right now this capability is limited in Menu Customizer because much of the data is not stored in settings, but in the DB persistently. 

There is also a problem now where if you just go in and preview changes to menus, additional nav menu item posts get created but never get cleaned up, unless a save happens. This will also pose a challenge for compatibility with [Customizer transactions](https://make.wordpress.org/core/2015/01/26/customizer-transactions-proposal/), since the premise is (and has been) that 100% of the settings data are represented in setting objects. But if upon saving the old menu item is deleted, and since Menu Customizer just stores references to post IDs, then loading Customizer transaction could very well reference a post ID that no longer exists and it would fail to restore a previous state.

# Todos

- [x] Normalize settings into two types: `nav_menu` and `nav_menu_item`. Create `WP_Customize_Setting` subclasses for each.
- [x] Properly create dynamic customizer settings (#70)
- [x] Store all menu item fields (array) inside of `nav_menu_item` Customizer settings ([todo comment](https://github.com/voldemortensen/menu-customizer/blob/44ef9d6fd9e303dd1a3fb60bb6ccb3110254e02e/menu-customizer.js#L1195) and [todo comment](https://github.com/voldemortensen/menu-customizer/blob/44ef9d6fd9e303dd1a3fb60bb6ccb3110254e02e/menu-customizer.js#L1923))
- [x] Update fields in control based on changes to underlying setting array.
- [ ] Re-sort menu items based on changes to a setting's parent item ID.
- [ ] Eliminate Ajax requests for updating menu items, creating new menus, deleting existing menus.
- [ ] Eliminate all cloning.

**Comment by westonruter** [comment]
Note that this represents a very big architectural change.

@ocean90 consideres also it a blocker: https://wordpress.slack.com/archives/core-customize/p1433154535002381

**Comment by westonruter** [comment]
The [Customize Posts plugin](https://github.com/xwp/wp-customize-posts) provides some examples for how Menu Customizer can implement full encapsulation of changes inside of Customizer settings.

Here is where it sets up the hooks to apply any incoming changes to post data or meta: https://github.com/xwp/wp-customize-posts/blob/master/php/class-wp-customize-posts-preview.php#L42-L53

Notice the full post data/meta array is getting added to the setting's value, not just the post ID, so no cloning is needed: https://github.com/xwp/wp-customize-posts/blob/master/php/class-wp-customize-posts.php#L90-L98
